import { Inter } from "next/font/google";
import Header from "../components/Header";
import Credit from "../components/Credit";

import Cart from "@/app/components/Cart/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "",
};
export interface CartLayoutProps {
  children: React.ReactNode;
}

export default function CartLayout({ children }: CartLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <hr />
        <div className="container">{children}</div>
        <Credit />
      </body>
    </html>
  );
}
